CREATE TABLE news (
idn INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
categoria VARCHAR( 20 ) NULL ,
autore VARCHAR( 15 ) NOT NULL ,
titolon VARCHAR( 50 ) NOT NULL ,
anno VARCHAR( 20 ) NOT NULL ,
mese VARCHAR( 30 ) NOT NULL ,
datan VARCHAR( 30 ) NOT NULL ,
teston VARCHAR( 20000 ) NOT NULL ,
msgemail VARCHAR( 5 ) NOT NULL
) ENGINE=InnoDB; 
CREATE TABLE utenti (
idu INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
nick VARCHAR( 10 ) NOT NULL ,
password VARCHAR( 30 ) NOT NULL ,
email VARCHAR( 30 ) NOT NULL ,
locazione VARCHAR( 20 ) NULL ,
datareg VARCHAR( 30 ) NOT NULL ,
UNIQUE (nick , password)
) ENGINE=InnoDB;
CREATE TABLE commenti (
idc INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
idn INT NOT NULL ,
idu INT NOT NULL ,
nick VARCHAR( 10 ) NOT NULL ,
datac VARCHAR( 30 ) NOT NULL ,
testoc VARCHAR( 5000 ) NOT NULL ,
FOREIGN KEY (idn) REFERENCES news(idn) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idu) REFERENCES utenti(idu) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE TABLE admin (
auid VARCHAR(10) NOT NULL,
apwd VARCHAR(10) NOT NULL,
aemail VARCHAR(30) NOT NULL,
blogtit VARCHAR(15) NOT NULL,
alocazione VARCHAR(20) NULL,
emailsrv VARCHAR(20) NOT NULL,
PRIMARY KEY (auid)
) ENGINE=InnoDB;
CREATE TABLE online (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
nick VARCHAR( 10 ) ,
lastlogin VARCHAR( 45 ) NOT NULL
) ENGINE=InnoDB;