'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.17929
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SendSMS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.webserviceX.NET", ConfigurationName:="SendSMS.SendSMSWorldSoap")>  _
    Public Interface SendSMSWorldSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceX.NET/sendSMS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sendSMS(ByVal FromEmailAddress As String, ByVal CountryCode As String, ByVal MobileNumber As String, ByVal Message As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SendSMSWorldSoapChannel
        Inherits SendSMS.SendSMSWorldSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SendSMSWorldSoapClient
        Inherits System.ServiceModel.ClientBase(Of SendSMS.SendSMSWorldSoap)
        Implements SendSMS.SendSMSWorldSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function sendSMS(ByVal FromEmailAddress As String, ByVal CountryCode As String, ByVal MobileNumber As String, ByVal Message As String) As String Implements SendSMS.SendSMSWorldSoap.sendSMS
            Return MyBase.Channel.sendSMS(FromEmailAddress, CountryCode, MobileNumber, Message)
        End Function
    End Class
End Namespace
